import { ConflictException, Injectable, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import * as argon2 from 'argon2';
import { PrismaService } from '../prisma.service';
import { RegisterDto } from './dto';
@Injectable()
export class AuthService {
  constructor(private readonly prisma: PrismaService, private readonly jwt: JwtService) {}
  async register(dto: RegisterDto) { const email = dto.email.toLowerCase().trim(); if (await this.prisma.user.findUnique({ where: { email } })) throw new ConflictException('Email is already registered'); const user = await this.prisma.user.create({ data: { email, passwordHash: await argon2.hash(dto.password), firstName: dto.firstName, lastName: dto.lastName } }); return this.issueTokens(user.id, user.email); }
  async login(email: string, password: string) { const user = await this.prisma.user.findUnique({ where: { email: email.toLowerCase().trim() } }); if (!user || !(await argon2.verify(user.passwordHash, password))) throw new UnauthorizedException('Invalid email or password'); return this.issueTokens(user.id, user.email); }
  async refresh(rawToken: string) { let payload: { sub: string; type: string }; try { payload = await this.jwt.verifyAsync(rawToken, { secret: process.env.JWT_REFRESH_SECRET }); } catch { throw new UnauthorizedException('Invalid refresh token'); } if (payload.type !== 'refresh') throw new UnauthorizedException('Invalid refresh token'); const stored = await this.prisma.refreshToken.findFirst({ where: { userId: payload.sub, revokedAt: null, expiresAt: { gt: new Date() } } }); if (!stored || !(await argon2.verify(stored.tokenHash, rawToken))) throw new UnauthorizedException('Refresh token revoked'); await this.prisma.refreshToken.update({ where: { id: stored.id }, data: { revokedAt: new Date() } }); const user = await this.prisma.user.findUniqueOrThrow({ where: { id: payload.sub } }); return this.issueTokens(user.id, user.email, stored.id); }
  async logout(rawToken: string) { const tokens = await this.prisma.refreshToken.findMany({ where: { revokedAt: null } }); for (const token of tokens) if (await argon2.verify(token.tokenHash, rawToken)) return this.prisma.refreshToken.update({ where: { id: token.id }, data: { revokedAt: new Date() } }); }
  async profile(userId: string) { const user = await this.prisma.user.findUniqueOrThrow({ where: { id: userId }, select: { id: true, email: true, firstName: true, lastName: true, createdAt: true } }); return user; }
  private async issueTokens(userId: string, email: string, replacedId?: string) { const refreshDays = Number(process.env.JWT_REFRESH_TTL_DAYS ?? 30); const accessToken = await this.jwt.signAsync({ sub: userId, email }, { secret: process.env.JWT_ACCESS_SECRET, expiresIn: 900 }); const refreshToken = await this.jwt.signAsync({ sub: userId, type: 'refresh' }, { secret: process.env.JWT_REFRESH_SECRET, expiresIn: refreshDays * 86400 }); const expiresAt = new Date(Date.now() + refreshDays * 86400000); const saved = await this.prisma.refreshToken.create({ data: { userId, tokenHash: await argon2.hash(refreshToken), expiresAt } }); if (replacedId) await this.prisma.refreshToken.update({ where: { id: replacedId }, data: { replacedByTokenId: saved.id } }); return { accessToken, refreshToken, tokenType: 'Bearer' }; }
}
