import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { ExtractionStatus, InvoiceStatus, Prisma, ReviewStatus } from '@prisma/client';
import { AuditService } from '../audit.service';
import { OrganizationAccessService } from '../organizations/organization-access.service';
import { PrismaService } from '../prisma.service';
import { CompleteUploadDto, InvoiceListQuery, ReviewInvoiceDto, UpdateInvoiceDto, UpdateLineItemDto, UploadIntentDto } from './dto';
import { InvoiceExtractionProcessor } from './extraction.processor';
import { InvoiceStorageService } from './storage.service';
const allowedTypes = new Set(['application/pdf', 'image/jpeg', 'image/png']); const maxFileSize = 15 * 1024 * 1024; const safeName = (name: string) => name.replace(/[^a-zA-Z0-9._-]/g, '_').slice(-160) || 'invoice';
const money = (value: unknown, name: string) => { if (value === null || value === undefined || value === '') return null; const parsed = new Prisma.Decimal(value as string | number); if (!parsed.isFinite() || parsed.lt(0)) throw new BadRequestException(`${name} cannot be negative`); return parsed; };
@Injectable()
export class InvoicesService {
  constructor(private readonly prisma: PrismaService, private readonly access: OrganizationAccessService, private readonly audit: AuditService, private readonly storage: InvoiceStorageService, private readonly extraction: InvoiceExtractionProcessor) {}
  private async location(userId: string, id: string) { const location = await this.prisma.restaurantLocation.findUnique({ where: { id } }); if (!location) throw new NotFoundException('Location not found'); await this.access.requireMember(userId, location.organizationId); return location; }
  private async invoice(userId: string, id: string) { const invoice = await this.prisma.invoice.findUnique({ where: { id } }); if (!invoice) throw new NotFoundException('Invoice not found'); await this.access.requireMember(userId, invoice.organizationId); return invoice; }
  private async vendor(organizationId: string, vendorId?: string | null) { if (!vendorId) return; const vendor = await this.prisma.vendor.findFirst({ where: { id: vendorId, organizationId } }); if (!vendor) throw new ForbiddenException('Vendor is not available'); }
  async uploadIntent(userId: string, data: UploadIntentDto) { if (!allowedTypes.has(data.mimeType)) throw new BadRequestException('Only PDF, JPG, JPEG, and PNG files are supported'); if (data.fileSize > maxFileSize) throw new BadRequestException('Invoice files must be 15 MB or smaller'); const location = await this.location(userId, data.restaurantLocationId); await this.vendor(location.organizationId, data.vendorId); const originalFileName = data.fileName.trim(); if (!originalFileName) throw new BadRequestException('File name is required'); const invoice = await this.prisma.invoice.create({ data: { organizationId: location.organizationId, restaurantLocationId: location.id, vendorId: data.vendorId, fileName: safeName(originalFileName), originalFileName, fileType: data.mimeType, fileSize: data.fileSize, storageKey: 'pending', createdByUserId: userId, status: InvoiceStatus.PROCESSING } }); const storageKey = `organizations/${location.organizationId}/locations/${location.id}/invoices/${invoice.id}/${safeName(originalFileName)}`; const saved = await this.prisma.invoice.update({ where: { id: invoice.id }, data: { storageKey } }); try { const uploadUrl = await this.storage.putUrl(storageKey, data.mimeType); await this.audit.log({ userId, organizationId: location.organizationId, action: 'invoice.created', entityType: 'Invoice', entityId: saved.id, metadata: { fileType: data.mimeType, fileSize: data.fileSize } }); return { invoice: saved, uploadUrl, headers: { 'Content-Type': data.mimeType } }; } catch (error) { await this.prisma.invoice.delete({ where: { id: invoice.id } }); throw error; } }
  async complete(userId: string, id: string, _data: CompleteUploadDto) { const invoice = await this.invoice(userId, id); await this.storage.exists(invoice.storageKey); const saved = await this.prisma.invoice.update({ where: { id }, data: { status: InvoiceStatus.UPLOADED } }); await this.audit.log({ userId, organizationId: invoice.organizationId, action: 'invoice.uploaded', entityType: 'Invoice', entityId: id }); if (this.extraction.isConfigured()) await this.startExtraction(userId, id); return saved; }
  async list(userId: string, query: InvoiceListQuery) { const location = await this.location(userId, query.restaurantLocationId); const endDate = query.endDate ? new Date(query.endDate) : undefined; if (endDate) endDate.setHours(23, 59, 59, 999); const invoices = await this.prisma.invoice.findMany({ where: { organizationId: location.organizationId, restaurantLocationId: location.id, vendorId: query.vendorId, status: query.status, createdAt: { gte: query.startDate ? new Date(query.startDate) : undefined, lte: endDate } }, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }] }); const vendors = await this.prisma.vendor.findMany({ where: { organizationId: location.organizationId, id: { in: invoices.map((i) => i.vendorId).filter(Boolean) as string[] } }, select: { id: true, name: true } }); const names = new Map(vendors.map((vendor) => [vendor.id, vendor.name])); return invoices.map((invoice) => ({ ...invoice, vendorName: invoice.vendorId ? names.get(invoice.vendorId) ?? null : null })); }
  async detail(userId: string, id: string) { const invoice = await this.invoice(userId, id); const vendor = invoice.vendorId ? await this.prisma.vendor.findFirst({ where: { id: invoice.vendorId, organizationId: invoice.organizationId }, select: { name: true } }) : null; return { ...invoice, vendorName: vendor?.name ?? invoice.extractedVendorName ?? null }; }
  async update(userId: string, id: string, data: UpdateInvoiceDto) { const invoice = await this.invoice(userId, id); await this.vendor(invoice.organizationId, data.vendorId); const saved = await this.prisma.invoice.update({ where: { id }, data: { vendorId: data.vendorId, invoiceNumber: data.invoiceNumber, invoiceDate: data.invoiceDate ? new Date(data.invoiceDate) : data.invoiceDate === null ? null : undefined, subtotal: money(data.subtotal, 'Subtotal'), tax: money(data.tax, 'Tax'), total: money(data.total, 'Total'), notes: data.notes, status: data.status ?? InvoiceStatus.COMPLETED } }); await this.audit.log({ userId, organizationId: invoice.organizationId, action: 'invoice.updated', entityType: 'Invoice', entityId: id }); return saved; }
  async startExtraction(userId: string, id: string) { const invoice = await this.invoice(userId, id); if (invoice.reviewStatus === ReviewStatus.REVIEWED) throw new BadRequestException('Reviewed invoices cannot be re-extracted'); if (!this.extraction.isConfigured()) throw new BadRequestException('Invoice extraction is not configured'); const isFreshProcessing = invoice.extractionStatus === ExtractionStatus.PROCESSING && invoice.extractionStartedAt && Date.now() - invoice.extractionStartedAt.getTime() < 10 * 60 * 1000; if (isFreshProcessing) return invoice; const saved = await this.prisma.invoice.update({ where: { id }, data: { extractionStatus: ExtractionStatus.PROCESSING, extractionStartedAt: new Date(), extractionCompletedAt: null, extractionError: null } }); await this.audit.log({ userId, organizationId: invoice.organizationId, action: 'invoice.extraction_started', entityType: 'Invoice', entityId: id }); setImmediate(() => void this.extraction.process(id, userId)); return saved; }
  async extractionStatus(userId: string, id: string) { const invoice = await this.invoice(userId, id); return { invoiceId: id, extractionStatus: invoice.extractionStatus, extractionConfidence: invoice.extractionConfidence, extractionError: invoice.extractionError, reviewStatus: invoice.reviewStatus, extractionStartedAt: invoice.extractionStartedAt, extractionCompletedAt: invoice.extractionCompletedAt }; }
  async lineItems(userId: string, id: string) { const invoice = await this.invoice(userId, id); return this.prisma.invoiceLineItem.findMany({ where: { invoiceId: id, organizationId: invoice.organizationId, restaurantLocationId: invoice.restaurantLocationId }, orderBy: [{ lineNumber: 'asc' }, { id: 'asc' }] }); }
  async updateLineItem(userId: string, invoiceId: string, lineItemId: string, data: UpdateLineItemDto) { const invoice = await this.invoice(userId, invoiceId); const item = await this.prisma.invoiceLineItem.findFirst({ where: { id: lineItemId, invoiceId, organizationId: invoice.organizationId, restaurantLocationId: invoice.restaurantLocationId } }); if (!item) throw new NotFoundException('Invoice line item not found'); if (invoice.reviewStatus === ReviewStatus.REVIEWED) throw new BadRequestException('Reviewed invoices cannot be edited'); const saved = await this.prisma.invoiceLineItem.update({ where: { id: lineItemId }, data: { rawDescription: data.rawDescription, sku: data.sku, quantity: data.quantity === undefined ? undefined : money(data.quantity, 'Quantity'), unit: data.unit, packSize: data.packSize, unitPrice: data.unitPrice === undefined ? undefined : money(data.unitPrice, 'Unit price'), extendedPrice: data.extendedPrice === undefined ? undefined : money(data.extendedPrice, 'Extended price'), category: data.category } }); await this.audit.log({ userId, organizationId: invoice.organizationId, action: 'invoice.line_item_corrected', entityType: 'InvoiceLineItem', entityId: lineItemId, metadata: { invoiceId } }); return saved; }
  async review(userId: string, id: string, data: ReviewInvoiceDto) { const invoice = await this.invoice(userId, id); await this.vendor(invoice.organizationId, data.vendorId); const invoiceDate = data.invoiceDate ? new Date(data.invoiceDate) : data.invoiceDate === null ? null : undefined; if (invoiceDate && invoiceDate > new Date(Date.now() + 86400000)) throw new BadRequestException('Invoice date cannot be in the future'); const saved = await this.prisma.invoice.update({ where: { id }, data: { vendorId: data.vendorId, extractedVendorName: data.vendorName === undefined ? undefined : data.vendorName?.trim() || null, invoiceNumber: data.invoiceNumber, invoiceDate, subtotal: money(data.subtotal, 'Subtotal'), tax: money(data.tax, 'Tax'), total: money(data.total, 'Total'), notes: data.notes } }); if (data.markReviewed) { const vendorPresent = Boolean(saved.vendorId || saved.extractedVendorName); if (!vendorPresent || !saved.invoiceDate || saved.total === null) throw new BadRequestException('Vendor, invoice date, and total are required before review'); const emptyLine = await this.prisma.invoiceLineItem.findFirst({ where: { invoiceId: id, rawDescription: '' } }); if (emptyLine) throw new BadRequestException('Every line item requires a description'); const reviewed = await this.prisma.invoice.update({ where: { id }, data: { reviewStatus: ReviewStatus.REVIEWED, reviewedAt: new Date(), reviewedByUserId: userId } }); await this.audit.log({ userId, organizationId: invoice.organizationId, action: 'invoice.marked_reviewed', entityType: 'Invoice', entityId: id }); return reviewed; } await this.audit.log({ userId, organizationId: invoice.organizationId, action: 'invoice.review_updated', entityType: 'Invoice', entityId: id }); return saved; }
  async delete(userId: string, id: string) { const invoice = await this.invoice(userId, id); await this.prisma.invoice.delete({ where: { id } }); try { await this.storage.remove(invoice.storageKey); } catch (error) { console.error(`Unable to remove invoice object ${id}`, error); } await this.audit.log({ userId, organizationId: invoice.organizationId, action: 'invoice.deleted', entityType: 'Invoice', entityId: id }); }
}
